project:
  type: website

website:
  title: "Mahesh Suryawanhi"
  navbar:

   right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: sketchy
    css: sample.css

editor: visual

